stages:
  - generate

generate_json:
  stage: generate
  image: python:3.10
  script:
    - pip install -r requirements.txt  # if needed
    - python fetch_strava_data.py
    - git config --global user.email "manueltiefenbacher998@gmail.com"
    - git config --global user.name "ManuelTiefenbacher"
    - git add StravaDashboard/output/activities.json
    - git commit -m "Update data.json [ci skip]" || echo "No changes to commit"
    - git push https://<CI_USER>:<CI_TOKEN>@gitlab.com/<username>/<repo>.git HEAD:main