name: Generate JSON Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the top of the hour (UTC)
  workflow_dispatch:  # This allows manual triggering as well
  
jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt  # If you have dependencies
          pip install requests

      - name: Run Python script to generate JSON
        run: |
          python fetch_strava_data.py

      - name: Configure Git
        run: |
          git config --global user.email "manueltiefenbacher998@gmail.com"
          git config --global user.name "ManuelTiefenbacher"

      - name: Commit and push generated data
        run: |
          git add output/data.json
          git commit -m "Update data.json [ci skip]" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
